[package]
name = "tmm"
version = "0.1.0"
authors = ["drootang <drootang@users.noreply.github.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.0"
exec = "0.3.1"
